FROM node:12.0-slim
ENV MONGODB_URI='mongodb://vivi:1234@boardgamescluster-shard-00-00-2fdfc.gcp.mongodb.net:27017,boardgamescluster-shard-00-01-2fdfc.gcp.mongodb.net:27017,boardgamescluster-shard-00-02-2fdfc.gcp.mongodb.net:27017/test?ssl=true&replicaSet=BoardgamesCluster-shard-0&authSource=admin&retryWrites=true&w=majority'
COPY . .
RUN npm install
CMD [ "node", "index.js" ]